version: '3'
services:
  app:
    build: .
    hostname: housing
    command: ["sh", "-c", "./set-env.sh -e dev && npm run start -- --host=0.0.0.0"]
    env_file:
      - variables.env
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "4201:4200"
networks:
  default:
    driver: bridge
